language: python

virtualenv:
    system_site_packages: true

python:
    - "2.7"
    - "3.4"

before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install -qq python-numpy python-gdal gdal-bin

install:
    - pip install .

script: nosetests

notifications:
  email:
    on_success: change
    on_failure: change
